apiVersion: batch/v1
kind: CronJob
metadata:
  name: polling-job
spec:
  schedule: "*/1 * * * *" #	Run every minute
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: polling-job
              image: wassmd/polling-job:latest
          restartPolicy: OnFailure